# Generated by Django 6.0.7 on 2026-07-20 09:02

import apps.events.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='event title')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_cover_upload_path, verbose_name='cover image')),
                ('event_date', models.DateField(verbose_name='event date')),
                ('event_time', models.TimeField(blank=True, null=True, verbose_name='event time')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('organizer_name', models.CharField(blank=True, max_length=255, verbose_name='organizer name')),
                ('organizer_contact', models.CharField(blank=True, max_length=50, verbose_name='organizer contact')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('college', 'College'), ('training', 'Training'), ('corporate', 'Corporate'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=20, verbose_name='event type')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('password_protected', 'Password Protected')], default='public', max_length=20, verbose_name='visibility')),
                ('password', models.CharField(blank=True, help_text='Required only for password protected events.', max_length=128, verbose_name='password')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='status')),
                ('gallery_expiry_date', models.DateField(blank=True, null=True, verbose_name='gallery expiry date')),
                ('allow_download', models.BooleanField(default=False, verbose_name='allow download')),
                ('show_watermark', models.BooleanField(default=True, verbose_name='show watermark')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
