# Generated by Django 6.0.7 on 2026-07-28 21:50

import apps.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_client_studio_event_studio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.events.models.event_cover_upload_path, verbose_name='cover image'),
        ),
    ]
