# Generated by Django 6.0.7 on 2026-07-20 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_client_studio_event_studio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('studio_owner', 'Studio Owner'), ('staff', 'Staff'), ('client', 'Client')], default='client', max_length=20, verbose_name='role'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=list, help_text='List of enabled permission codenames.', verbose_name='permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='events.studio', verbose_name='studio')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'staff'}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'studio'), name='unique_staff_per_studio')],
            },
        ),
    ]
