# Generated by Django 6.0.7 on 2026-07-20 09:12

import apps.albums.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=255, verbose_name='album title')),
                ('slug', models.SlugField(blank=True, max_length=280, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.albums.models.album_cover_upload_path, verbose_name='cover image')),
                ('album_order', models.PositiveIntegerField(default=0, verbose_name='album order')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'album',
                'verbose_name_plural': 'albums',
                'ordering': ['album_order', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'title'), name='unique_album_title_per_event'), models.UniqueConstraint(fields=('event', 'slug'), name='unique_album_slug_per_event')],
            },
        ),
    ]
