# Generated by Django 6.0.7 on 2026-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_order',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='album order'),
        ),
    ]
