# Generated by Django 6.0.7 on 2026-07-28 21:50

import apps.albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_album_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.albums.models.album_cover_upload_path, verbose_name='cover image'),
        ),
    ]
