# Generated by Django 6.0.7 on 2026-07-20 10:52

import apps.qr.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True, verbose_name='uuid')),
                ('token', models.CharField(default=apps.qr.models.generate_secure_token, editable=False, max_length=64, unique=True, verbose_name='secure token')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=apps.qr.models.qr_image_upload_path, verbose_name='qr image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('scan_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='scan count')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='last scanned at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'qr code',
                'verbose_name_plural': 'qr codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
