# Generated by Django 6.0.7 on 2026-07-20 09:40

import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(editable=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(max_length=500, upload_to=apps.media.models.media_file_upload_path, verbose_name='file')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.media.models.media_thumbnail_upload_path, verbose_name='thumbnail')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10, verbose_name='media type')),
                ('file_size', models.BigIntegerField(default=0, editable=False, verbose_name='file size')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds.', null=True, verbose_name='duration (seconds)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='mime type')),
                ('download_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='download count')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='view count')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('status', models.CharField(choices=[('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='albums.album', verbose_name='album')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event', verbose_name='event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'ordering': ['-created_at'],
            },
        ),
    ]
