# Generated by Django 6.0.7 on 2026-07-21 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_client_studio_event_studio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Name of the client gallery.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='URL-friendly identifier for this gallery.', max_length=280, unique=True, verbose_name='slug')),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('password_protected', 'Password Protected'), ('private', 'Private')], default='private', help_text='Who can access this gallery.', max_length=20, verbose_name='access type')),
                ('gallery_password', models.CharField(blank=True, help_text='Password required to access this gallery. Leave empty for public or private access.', max_length=128, verbose_name='gallery password')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token for sharing the gallery link.', unique=True, verbose_name='share token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the gallery.', null=True, verbose_name='expires at')),
                ('allow_download', models.BooleanField(default=True, help_text='Allow users to download photos from this gallery.', verbose_name='allow download')),
                ('allow_favorites', models.BooleanField(default=True, help_text='Allow users to mark photos as favorites.', verbose_name='allow favorites')),
                ('event', models.ForeignKey(help_text='The event this gallery belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='client_galleries', to='events.event', verbose_name='event')),
            ],
            options={
                'verbose_name': 'client gallery',
                'verbose_name_plural': 'client galleries',
                'ordering': ['display_order', '-pk'],
                'abstract': False,
            },
        ),
    ]
