# Generated by Django 6.0.7 on 2026-07-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for the user who favorited this photo.', max_length=128, verbose_name='session id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gallery.clientgallery', verbose_name='gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_favorites', to='media.media', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'gallery favorite',
                'verbose_name_plural': 'gallery favorites',
                'ordering': ['-created_at'],
                'unique_together': {('gallery', 'photo', 'session_id')},
            },
        ),
    ]
