# Generated by Django 6.0.7 on 2026-07-21 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_add_galleryfavorite'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, verbose_name='session id')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='downloaded at')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='gallery.clientgallery', verbose_name='gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='media.media', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'gallery download log',
                'verbose_name_plural': 'gallery download logs',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
