# Generated by Django 6.0.7 on 2026-07-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_add_gallerydownloadlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128, verbose_name='session id')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip address')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('referrer', models.URLField(blank=True, verbose_name='referrer')),
                ('visited_at', models.DateTimeField(auto_now_add=True, verbose_name='visited at')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='gallery.clientgallery', verbose_name='gallery')),
            ],
            options={
                'verbose_name': 'gallery visit',
                'verbose_name_plural': 'gallery visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
