# Generated by Django 6.0.7 on 2026-07-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LensVault', help_text='The name of the site displayed in the header and title tags.', max_length=255, verbose_name='site name')),
                ('site_tagline', models.CharField(blank=True, help_text='A short tagline shown below the site name.', max_length=255, verbose_name='site tagline')),
                ('site_description', models.TextField(blank=True, help_text='A brief description of the site for SEO and meta tags.', verbose_name='site description')),
                ('logo', models.ImageField(blank=True, help_text='Upload the site logo. Recommended size: 200x200px.', null=True, upload_to='cms/logo/', verbose_name='logo')),
                ('favicon', models.ImageField(blank=True, help_text='Upload the favicon. Recommended size: 64x64px.', null=True, upload_to='cms/favicon/', verbose_name='favicon')),
                ('support_email', models.EmailField(blank=True, help_text='Email address for customer support.', max_length=254, verbose_name='support email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address of the business.', verbose_name='address')),
                ('facebook_url', models.URLField(blank=True, help_text='Link to the Facebook page.', verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Link to the Instagram profile.', verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, help_text='Link to the YouTube channel.', verbose_name='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='Link to the LinkedIn profile.', verbose_name='LinkedIn URL')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active SiteSettings record should exist at a time.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
                'ordering': ['-pk'],
            },
        ),
    ]
