# Generated by Django 6.0.7 on 2026-07-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, help_text='Small text displayed above the main heading.', max_length=255, verbose_name='badge text')),
                ('heading', models.CharField(help_text='Main hero heading.', max_length=255, verbose_name='heading')),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text displayed below the heading.', verbose_name='subtitle')),
                ('primary_button_text', models.CharField(blank=True, help_text='Text for the primary call-to-action button.', max_length=255, verbose_name='primary button text')),
                ('primary_button_url', models.CharField(blank=True, help_text='URL for the primary button.', max_length=255, verbose_name='primary button URL')),
                ('secondary_button_text', models.CharField(blank=True, help_text='Text for the secondary button.', max_length=255, verbose_name='secondary button text')),
                ('secondary_button_url', models.CharField(blank=True, help_text='URL for the secondary button.', max_length=255, verbose_name='secondary button URL')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image shown in the visual area.', null=True, upload_to='cms/hero/', verbose_name='hero image')),
                ('background_image', models.ImageField(blank=True, help_text='Background image for the hero section.', null=True, upload_to='cms/hero/', verbose_name='background image')),
                ('stat_1_number', models.CharField(blank=True, help_text='First statistic value, e.g. 2500+.', max_length=50, verbose_name='statistic 1 number')),
                ('stat_1_label', models.CharField(blank=True, help_text='First statistic label, e.g. Photos.', max_length=255, verbose_name='statistic 1 label')),
                ('stat_2_number', models.CharField(blank=True, help_text='Second statistic value, e.g. 150.', max_length=50, verbose_name='statistic 2 number')),
                ('stat_2_label', models.CharField(blank=True, help_text='Second statistic label, e.g. Events.', max_length=255, verbose_name='statistic 2 label')),
                ('stat_3_number', models.CharField(blank=True, help_text='Third statistic value, e.g. 98%.', max_length=50, verbose_name='statistic 3 number')),
                ('stat_3_label', models.CharField(blank=True, help_text='Third statistic label, e.g. Client Satisfaction.', max_length=255, verbose_name='statistic 3 label')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active HeroSection should exist at a time.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
            ],
            options={
                'verbose_name': 'hero section',
                'verbose_name_plural': 'hero sections',
                'ordering': ['display_order', '-pk'],
            },
        ),
    ]
