# Generated by Django 6.0.7 on 2026-07-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Feature card title.', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Short description shown inside the feature card.', verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon string, e.g. 📅, 🖼️, 🔒.', max_length=255, verbose_name='icon')),
                ('icon_background', models.CharField(default='primary', help_text='Background style for the icon container. Recommended value: primary.', max_length=50, verbose_name='icon background')),
                ('accent_color', models.CharField(blank=True, help_text='Optional accent color override for this feature card.', max_length=50, verbose_name='accent color')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this feature on the homepage.', verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this feature in a featured area if supported.', verbose_name='featured')),
                ('link', models.CharField(blank=True, help_text='Optional URL when the feature card is clicked.', max_length=255, verbose_name='link')),
                ('button_text', models.CharField(blank=True, help_text='Optional CTA button text for this feature card.', max_length=255, verbose_name='button text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
                'ordering': ['display_order', '-pk'],
            },
        ),
    ]
