# Generated by Django 6.0.7 on 2026-07-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_herosection_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('page_key', models.CharField(help_text='Unique identifier for this page, e.g. home, events, gallery.', max_length=100, unique=True, verbose_name='page key')),
                ('meta_title', models.CharField(blank=True, help_text='Title shown in browser tab and search results.', max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, help_text='Short description for search engines.', verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for search engines.', max_length=255, verbose_name='meta keywords')),
                ('og_title', models.CharField(blank=True, help_text='Title used when sharing on social media.', max_length=255, verbose_name='Open Graph title')),
                ('og_description', models.TextField(blank=True, help_text='Description used when sharing on social media.', verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, help_text='Image shown when sharing on social media.', null=True, upload_to='cms/seo/', verbose_name='Open Graph image')),
                ('canonical_url', models.URLField(blank=True, help_text='Preferred URL for this page to avoid duplicate content issues.', verbose_name='canonical URL')),
                ('robots', models.CharField(blank=True, help_text='Search engine crawl instructions, e.g. index, follow.', max_length=255, verbose_name='robots')),
            ],
            options={
                'verbose_name': 'SEO settings',
                'verbose_name_plural': 'SEO settings',
                'ordering': ['page_key'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active'),
        ),
    ]
