# Generated by Django 6.0.7 on 2026-07-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_seosettings_alter_feature_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='Human-readable name for this media asset.', max_length=255, verbose_name='title')),
                ('file', models.FileField(help_text='Upload the media file.', upload_to='cms/media/', verbose_name='file')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility and SEO.', max_length=255, verbose_name='alt text')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='image', help_text='Type of media asset.', max_length=20, verbose_name='media type')),
                ('category', models.CharField(blank=True, help_text='Optional category for grouping assets.', max_length=100, verbose_name='category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for filtering.', max_length=255, verbose_name='tags')),
                ('is_public', models.BooleanField(default=True, help_text='Allow this asset to be used on public pages.', verbose_name='public')),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'ordering': ['display_order', '-pk'],
                'abstract': False,
            },
        ),
    ]
