# Generated by Django 6.0.7 on 2026-07-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_mediaasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('theme_name', models.CharField(help_text='Name of the theme, e.g. Default, Dark, Ocean.', max_length=255, verbose_name='theme name')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Main brand color in hex format. Default: #6366f1.', max_length=10, verbose_name='primary color')),
                ('secondary_color', models.CharField(default='#8b5cf6', help_text='Secondary brand color in hex format. Default: #8b5cf6.', max_length=10, verbose_name='secondary color')),
                ('accent_color', models.CharField(default='#f59e0b', help_text='Accent color in hex format. Default: #f59e0b.', max_length=10, verbose_name='accent color')),
                ('font_family', models.CharField(default='Inter', help_text='Primary font family for the theme.', max_length=100, verbose_name='font family')),
                ('heading_font', models.CharField(default='Inter', help_text='Font family for headings.', max_length=100, verbose_name='heading font')),
                ('body_font', models.CharField(default='Inter', help_text='Font family for body text.', max_length=100, verbose_name='body font')),
                ('border_radius', models.CharField(choices=[('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large'), ('full', 'Full')], default='lg', help_text='Corner radius for cards, buttons, and inputs.', max_length=50, verbose_name='border radius')),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill')], default='rounded', help_text='Global button shape style.', max_length=20, verbose_name='button style')),
                ('container_width', models.IntegerField(default=1280, help_text='Maximum content width in pixels. Default: 1280.', verbose_name='container max width')),
                ('card_shadow', models.CharField(choices=[('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large')], default='md', help_text='Shadow depth for cards.', max_length=50, verbose_name='card shadow')),
                ('glass_effect_enabled', models.BooleanField(default=True, help_text='Enable glassmorphism effects on cards and navbars.', verbose_name='glass effect enabled')),
                ('is_default', models.BooleanField(default=False, help_text='Only one default theme can exist.', verbose_name='default')),
            ],
            options={
                'verbose_name': 'theme settings',
                'verbose_name_plural': 'theme settings',
                'ordering': ['-is_default', 'display_order', '-pk'],
                'abstract': False,
            },
        ),
    ]
