# Generated by Django 6.0.7 on 2026-07-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_themesettings'),
        ('gallery', '0004_add_gallery_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('heading', models.CharField(help_text='Main CTA heading.', max_length=255, verbose_name='heading')),
                ('description', models.TextField(blank=True, help_text='Supporting text below the heading.', verbose_name='description')),
                ('primary_button_text', models.CharField(blank=True, help_text='Text for the primary button.', max_length=255, verbose_name='primary button text')),
                ('primary_button_url', models.CharField(blank=True, help_text='URL for the primary button.', max_length=255, verbose_name='primary button URL')),
                ('secondary_button_text', models.CharField(blank=True, help_text='Text for the secondary button.', max_length=255, verbose_name='secondary button text')),
                ('secondary_button_url', models.CharField(blank=True, help_text='URL for the secondary button.', max_length=255, verbose_name='secondary button URL')),
            ],
            options={
                'verbose_name': 'CTA section',
                'verbose_name_plural': 'CTA sections',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the trust heading.', max_length=255, verbose_name='eyebrow')),
                ('heading', models.CharField(help_text='Main trust section heading.', max_length=255, verbose_name='heading')),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text below the heading.', verbose_name='subtitle')),
                ('hub_label', models.CharField(blank=True, help_text='Optional label shown near the center hub.', max_length=255, verbose_name='hub label')),
            ],
            options={
                'verbose_name': 'trust section',
                'verbose_name_plural': 'trust sections',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='Workflow step title.', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Short description shown for this step.', verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon string, e.g. 📅, 🖼️, 🔒.', max_length=255, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'workflow step',
                'verbose_name_plural': 'workflow steps',
                'ordering': ['display_order', '-pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='herosection',
            name='rotating_words',
            field=models.CharField(blank=True, help_text='Comma-separated words for the rotating text animation, e.g. Timeless., Personal., Unforgettable.', max_length=255, verbose_name='rotating words'),
        ),
        migrations.CreateModel(
            name='GalleryShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the gallery heading.', max_length=255, verbose_name='eyebrow')),
                ('heading', models.CharField(help_text='Main gallery section heading.', max_length=255, verbose_name='heading')),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text below the heading.', verbose_name='subtitle')),
                ('featured_gallery', models.ForeignKey(blank=True, help_text='The main featured gallery displayed prominently.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_gallery_showcase', to='gallery.clientgallery', verbose_name='featured gallery')),
                ('selected_galleries', models.ManyToManyField(blank=True, help_text='Additional galleries to display in the showcase.', related_name='gallery_showcases', to='gallery.clientgallery', verbose_name='selected galleries')),
            ],
            options={
                'verbose_name': 'gallery showcase',
                'verbose_name_plural': 'gallery showcases',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrustItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(help_text='Trust card title.', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Short description shown inside the trust card.', verbose_name='description')),
                ('badge', models.CharField(blank=True, help_text='Small status badge, e.g. ENCRYPTED, FAST.', max_length=50, verbose_name='badge')),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon string, e.g. 🔒, ⚡, 🔗, ✨.', max_length=255, verbose_name='icon')),
                ('section', models.ForeignKey(help_text='The trust section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.trustsection', verbose_name='section')),
            ],
            options={
                'verbose_name': 'trust item',
                'verbose_name_plural': 'trust items',
                'ordering': ['display_order', '-pk'],
                'abstract': False,
            },
        ),
    ]
