# Generated by Django 6.0.7 on 2026-07-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_ctasection_trustsection_workflowstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Show this record on the site.', verbose_name='active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('eyebrow', models.CharField(blank=True, help_text='Small text above the workflow heading.', max_length=255, verbose_name='eyebrow')),
                ('heading', models.CharField(help_text='Main workflow section heading.', max_length=255, verbose_name='heading')),
                ('subtitle', models.TextField(blank=True, help_text='Supporting text below the heading.', verbose_name='subtitle')),
            ],
            options={
                'verbose_name': 'workflow section',
                'verbose_name_plural': 'workflow sections',
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
